audio_vae:
  tod_vae_ckpt: /cpfs01/projects-HDD/cfff-721febfbdfb0_HDD/public/chunyu/model/MMAudio/ext_weights/v1-16.pth
  bigvgan_vocoder_ckpt: /cpfs01/projects-HDD/cfff-721febfbdfb0_HDD/public/chunyu/model/MMAudio/ext_weights/best_netG.pt
  mode: 16k
  need_vae_encoder: True
